name: Compile Sketches
on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./examples
          libraries: |
            - source-path: ./
              destination-name: AbleButtons
